[package]
name = "svabresp"
version = "0.1.0"
edition = "2024"

[dependencies]
probabilistic-models = { path = "../probabilistic-models" }
probabilistic-model-algorithms = { path = "../probabilistic-model-algorithms" }