[package]
name = "prism-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
prism-model = { path = "../prism-model" }
probabilistic-properties = { path = "../probabilistic-properties" }
chumsky = "1.0.0-alpha.8"